name: publish Node.js Package

on:
  push:
    branches:
      - package

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup GIT
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        registry-url: https://npm.pkg.github.com/
        scope: '@kodingkeun'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Install Dependencies
      run: yarn
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish in Github Package
      run: yarn version --minor && git push --tags && git push && yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}